# Gradle Build Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Common Mod Properties (Shared across Fabric & NeoForge)
mod_id=mc_ever_light
mod_name=EverLight
mod_version=1.0.0
mod_authors=datsuns
mod_license=MIT
mod_homepage=https://github.com/datsuns/mc-ever-light
mod_sources=https://github.com/datsuns/mc-ever-light
mod_description=Screen Brightness Mod (Fullbright) for Minecraft 26.2
maven_group=me.datsuns.everlight
archives_base_name=mc_ever_light
minecraft_version=26.2

# Fabric Specific Properties
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.154.2+26.2
modmenu_version=20.0.1

# NeoForge Specific Properties
neo_version=26.2.0.32-beta
neoforge_moddev_version=2.0.141

# Modrinth Publishing Properties
modrinth_id=uIOnStsQ
minecraft_version_range=[26.2,26.3)
neo_version_range=[26.2.0,)
loader_version_range=[4,)
useLegacyMixinAp=true
