modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${mod_sources}/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mc_ever_light.neoforge.mixins.json"

[[dependencies.mc_ever_light]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mc_ever_light]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
